### ISSUE TITLE
[BUG] calcFitHeight calculates wrong value

### ISSUE THREAD

**Issue by AE1NS** [roman-rr/cupertino-pane#192]
**Describe the bug**
When using the fitHeight option, changing the drawer content from 200px to 100px and call calcFitHeight(), the content grows instead of shrinking.

**To Reproduce**
https://jsfiddle.net/jwe3r4uy/

**Expected behavior**
When changing the content from 200px to 100px, the drawer should shrink.

**Comment by AE1NS** [comment]
Do you think there is any workaround till its fixed? When I see it correctly, its caused by an interal variable that holds the previous value and is added as 'diff'. So currently I dont see a possible workaround, but maybe you have an idea.

**Comment by roman-rr** [comment]
@AE1NS ill check it in few day, thank you for issue

**Comment by roman-rr** [comment]
@AE1NS Please check version from master branch. If that's fixed i gonna push the tag version up.

**Comment by AE1NS** [comment]
Just tested it. Looks good, thank you!

**Comment by AE1NS** [comment]
Unfortunately there is another issue now. When you change the content height to more than 100% of the pane and change it back, the calculated height is wrong and too low. Here is an example:
https://jsfiddle.net/0oy71j2c/

**Comment by roman-rr** [comment]
@AE1NS big thank you for your support. Should be fixed and pushed `v1.3.13`.
FitHeight logic quite fresh and I wouldn't able to test all cases, do not hesitate to create new tickers if so. 
Maybe it is a good point to create automated screenshot testing with cypress, to reduce such cases.

**Comment by AE1NS** [comment]
Unfortunately there seems still to be issues with calcFitHeight.

Could you have a look to this example:
https://jsfiddle.net/nzb4gphe/

At the end, the container does not have the correct height, its larger.

**Comment by roman-rr** [comment]
@AE1NS Thank you for report. Does it happens after recent tag release `v.1.3.31` ?

**Comment by AE1NS** [comment]
I dont know exactly. We used 1.3.21 and I had problems with wrong pane heights. I had situations, where the pane sometimes had a wrong height and calcFitHeight didnt solve it. Thats why I upgraded to latest and created the jsfiddle based on it. But I dont know if its the same cause of the problem.
When I had the problem in our app, I had to remove the height values of the wrapper container and then calcFitHeight fixed it, but with ugly animations because some bottom shaddow of a wrapper container was visible while animation.

**Comment by roman-rr** [comment]
@AE1NS Ok I'll re-check.

**Comment by AE1NS** [comment]
I just see thats its even more problematic on 1.3.31 than on 1.3.21. With 1.3.31 I have more cases where the pane is not calculated correctly. In my case the pane gets not shrinked and stays at the full previous height.

**Comment by roman-rr** [comment]
@AE1NS 
Please check your example and also https://jsfiddle.net/aenfx4gc/
Looks like all cases are covered properly.

**Comment by AE1NS** [comment]
Thanks for the update! Could you have a look at my jsfiddle example again. Its technically working now, but shouldnt be the pane still be 100% height when the animation starts (as it worked before)? Now the container 'jumps' small to 100px and animates down afterwards. Thats the same effect as in the previous version, when I just removed the 'height' property and called calcFitHeight and looks really strange as I also noted in my last comment (with the bottom shadow).

**Comment by roman-rr** [comment]
@AE1NS You are absolutely right. I will improve transitions to be a smooth.

**Comment by roman-rr** [comment]
@AE1NS Please check.

**Comment by AE1NS** [comment]
Looks better, but there are still issues. When `* { box-sizing: border-box; }` is set for the application, the container height is wrong. In my example above, the wrapper has 100px height and the padding is applied without changing the container height. The child container also has 100px height and is pushed out at the bottom.

**Comment by roman-rr** [comment]
@AE1NS Check all your cases, reviewed algorithm and seems like works now for all. 
Thank you for big help to improvements. Please check.

**Comment by AE1NS** [comment]
There seems to be another strange behavior: https://jsfiddle.net/8dy0wjt2/
The last container has a wrong height. If calcFitHeight is called after another second its correctly, buts it seems like another bug no?

**Comment by roman-rr** [comment]
@AE1NS Thank you again. Fixed also. If you wish, you can make a pull request for some more bugs you find in future. 
And I will complete pull with fixes, so you can be in contributors.

**Comment by AE1NS** [comment]
Looks good for the moment :)

I really appreciate your work and this awesome support! Thank you very much!

**Comment by luckashenri** [comment]
I'm using latest version, 1.3.51, and I just can't call this function. It says '.calcFitHeight is not a function'.
I'm using overflow-y to set the scrollable area, but everytime I navigate it breaks, it jjust doesn't calculate the height, therefore no scroll.
I wanted to trigger it manually if it's the case, but I can't call this function u guys were talking about.
@roman-rr @AE1NS

**Comment by roman-rr** [comment]
@luckashenri please create new issue and show your code. I just checked and it works on my side. 
https://jsfiddle.net/romantonoff/sq2va3xc/
